#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
#
# Add icons of general interest
#
/control/execute icons.mac
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run "beamOn 100" "/run/beamOn 100"
/gui/addButton run run1 "/control/execute run.mac"
#
# Gun menu :
/gui/addMenu gps GPS
/gui/addButton gps "e-"      "/gps/particle e-"
/gui/addButton gps "e+"      "/gps/particle e+"
/gui/addButton gps "pi0"     "/gps/particle pi0"
/gui/addButton gps "pi+"     "/gps/particle pi+"
/gui/addButton gps "neutron" "/gps/particle neutron"
#/gui/addButton gps "proton"  "/gps/particle proton"
#/gui/addButton gps "Random Primary type"  "/tutorial/generator/randomizePrimary true"
#/gui/addButton gps "p=100 MeV" "/tutorial/generator/momentum 0.1 GeV"
#/gui/addButton gps "p=500 MeV" "/tutorial/generator/momentum 0.5 GeV"
#/gui/addButton gps "p=1 GeV" "/tutorial/generator/momentum 1 GeV"
#/gui/addButton gps "p=5 GeV" "/tutorial/generator/momentum 5 GeV"
#/gui/addButton gps "sigma_p=0 MeV" "/tutorial/generator/sigmaMomentum 0 MeV"
#/gui/addButton gps "sigma_p=50 MeV" "/tutorial/generator/sigmaMomentum 50 MeV"
#/gui/addButton gps "sigma_p=100 MeV" "/tutorial/generator/sigmaMomentum 100 MeV"
#/gui/addButton gps "sigma_angle=0 rad" "/tutorial/generator/sigmaAngle 0 rad"
#/gui/addButton gps "sigma_angle=1 mrad" "/tutorial/generator/sigmaAngle 0.001 rad"
#/gui/addButton gps "sigma_angle=10 mrad" "/tutorial/generator/sigmaAngle 0.01 rad"
#
# Field menu :
/gui/addMenu field Field
/gui/addButton field "off"       "/tutorial/field/value 0   tesla"
/gui/addButton field "0.2 tesla" "/tutorial/field/value 0.2 tesla"
/gui/addButton field "2.0 tesla" "/tutorial/field/value 2.0 tesla"
#
# Arm menu:
/gui/addMenu arm "Rotate Arm"
/gui/addButton arm "0 deg" "/tutorial/detector/armAngle 0"
/gui/addButton arm "30 deg" "/tutorial/detector/armAngle 30 deg"
/gui/addButton arm "60 deg" "/tutorial/detector/armAngle 60 deg"
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wireframe"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# User defined icon :
#/gui/addIcon "Run beam on" user_icon "/run/beamOn 1" run.png 
