##########################################################
#                                                        #
#                   AmBeSource Standard Macro                 #
#                                                        #
##########################################################


#PreInit:

#  Define the level of verbosity of messages
# options: debugging, development, trace, routine, warning, error
# default: routine
/ds/manager/log development
/ds/manager/log trace
/ds/manager/verbosity -1
/ds/manager/checkoverlap 0
/ds/manager/eventcounter 50000
/ds/manager/writephotons 0
/ds/manager/writedeposits 1
/ds/manager/writedaughters 1
#/ds/manager/optics_tuning ../data/detector/DSOptics.dat
/ds/manager/fast_simulation 1

#Detector configuration: TPC+NV+WT (0) - TPC+NW (1) - TPC (2) - NV+WT (3) - Tester (4) - TPC_DS10 (5)
/ds/detector/configuration 0
/ds/detector/ExtLarScintillating 1
/ds/detector/vetoyieldfactor 0.0

/ds/physics/optics 3
#/ds/physics/HPRangeCuts false
/ds/physics/killS2 1
/ds/physics/tuned200V 1

# Define output file name
/run/filename /scratch/darkside/reinhol1/MC/amc_calis_test

# Define  random seed
/run/heprandomseed 12345679

#Define the hadronic physics list (none HP Shielding QGSP_BERT_HP QGSP_BIC_HP FTF_BIC_HP FTFP_BERT_HP)
/ds/physics/hadronic_list HP

#Define the EM physics list (standard livermore)
/ds/physics/em_list livermore

#/ds/physics/optics 0 
#/ds/physics/killS1S2 1
#/ds/physics/killS2 1
#/ds/physics/scaleS2 3
#/ds/physics/DriftField 1 kV/cm
#/ds/physics/ExtractionField 2.8 kV/cm

#place the source holder of CALIS before initalize (TPC center along z: -3.5 cm, cryostat radius: 32 cm)
/ds/detector/holderZ -1.05 cm
/ds/detector/holderRadius 32. cm
/ds/detector/holderPhi 0. degree


#-----------------------------------
/run/initialize
#-----------------------------------

#PostInit:

/ds/generator/select AmCSource
#simulates the neutron spectrum of the gamma-less AmC source
#please note that the 60 keV gammas from the 241Am are not simulated/ considered in this generator.

#the neutron energy correlates with the angle of emission because of the alpha kinetic energy being angle dependent. Therefore set a normal vector of the source disc (consider it having the shape of a flat coin).
#/ds/generator/AmC/setNormalVector 0 -1 0

#/ds/generator/sphere_radius 1 mm
#/ds/generator/set_center 0. 100. 0. cm
/ds/generator/holderSource_on 1

# Define the number of events
/run/beamOn 10000
